<h1 align="center" style="color: #87CEEB;">Customer-Churn-Prediction-using-ANN<h1>

In [81]:
import pandas as pd

In [82]:
df=pd.read_csv("archive\Churn_Modelling.csv")

In [83]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [85]:
df.duplicated().sum()

0

In [86]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [87]:
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True)

In [88]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [90]:
df=pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True,dtype=int)

In [91]:
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1                  0   
1                  1        112542.58       0                  0   
2                  0        113931.57       1                  0   
3                  0         93826.63       0                  0   
4                  1         79084.10       0                  0   
...              ...              ...     ...                ...   
9995               0         96270.64       0                  0   
9996               1        101699.77       0                  0   
9997               1         42085.58       1                  0   
9998               0         92888.52       1                  1   
9999               0         38190.78       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [92]:
from sklearn.model_selection import train_test_split

X=df.drop(columns=["Exited"])
y=df['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [93]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [94]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [95]:
import tensorflow
from tensorflow import keras

In [96]:
from keras import Sequential
from tensorflow.keras.layers import Dense

In [97]:
model=Sequential()

In [98]:
model.add(Dense(3,activation="sigmoid",input_dim=11))
model.add(Dense(1,activation="sigmoid"))

In [99]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 3)                 36        
                                                                 
 dense_11 (Dense)            (None, 1)                 4         
                                                                 
Total params: 40 (160.00 Byte)
Trainable params: 40 (160.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [100]:
model.compile(loss="binary_crossentropy",optimizer='Adam')

In [101]:
model.fit(X_train_scaled,y_train,epochs=10)

Epoch 1/10


250/250 [==============================] - 1s 1ms/step - loss: 0.9873
Epoch 2/10
250/250 [==============================] - 0s 1ms/step - loss: 0.7521
Epoch 3/10
250/250 [==============================] - 0s 1ms/step - loss: 0.6305
Epoch 4/10
250/250 [==============================] - 0s 1ms/step - loss: 0.5689
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 0.5370
Epoch 6/10
250/250 [==============================] - 0s 1ms/step - loss: 0.5184
Epoch 7/10
250/250 [==============================] - 0s 1ms/step - loss: 0.5043
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4918
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4803
Epoch 10/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4694


In [102]:
model.layers[0].get_weights()

[array([[ 0.3475555 ,  0.34172934, -0.28475103],
        [-1.1417904 ,  0.4493593 ,  1.1265339 ],
        [ 0.3338464 , -0.24706057,  0.20650569],
        [-0.3857592 ,  0.05249841,  0.494788  ],
        [-0.09445819, -0.28533685,  0.13787933],
        [-0.19342732, -0.37274125, -0.06671996],
        [ 0.40157214, -0.49510545, -0.928507  ],
        [-0.181087  ,  0.17483911,  0.18346001],
        [-0.78753763,  1.0282607 ,  0.2199339 ],
        [ 0.26634097, -0.05442199, -0.16256328],
        [ 0.2940805 , -0.633002  , -0.31008288]], dtype=float32),
 array([ 0.28788036, -0.61709154, -0.62736136], dtype=float32)]

In [103]:
y_log=model.predict(X_test_scaled)

63/63 [==============================] - 0s 785us/step


In [104]:
import numpy as np
y_pred=np.where(y_log>0.5,1,0)

In [105]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1585
           1       0.00      0.00      0.00       415

    accuracy                           0.79      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.63      0.79      0.70      2000



c:\Users\salma\anaconda3\envs\DeepLearningCampusX\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\salma\anaconda3\envs\DeepLearningCampusX\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\salma\anaconda3\envs\DeepLearningCampusX\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_

In [106]:
model2=Sequential()

In [107]:
X_train.shape

(8000, 11)

In [108]:
model2.add(Dense(6,input_dim=11,activation='relu'))

In [109]:
model2.add(Dense(3,activation='relu'))

In [110]:
model2.add(Dense(1,activation='sigmoid'))

In [111]:
model2.compile(loss="binary_crossentropy",optimizer='Adam',metrics=['accuracy'])

In [112]:
model2.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 [==============================] - 1s 2ms/step - loss: 0.5830 - accuracy: 0.7972 - val_loss: 0.5060 - val_accuracy: 0.7975
Epoch 2/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4719 - accuracy: 0.7972 - val_loss: 0.4556 - val_accuracy: 0.7975
Epoch 3/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4463 - accuracy: 0.7972 - val_loss: 0.4395 - val_accuracy: 0.7975
Epoch 4/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4368 - accuracy: 0.7972 - val_loss: 0.4314 - val_accuracy: 0.7975
Epoch 5/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4308 - accuracy: 0.7972 - val_loss: 0.4247 - val_accuracy: 0.7975
Epoch 6/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4259 - accuracy: 0.7972 - val_loss: 0.4184 - val_accuracy: 0.7975
Epoch 7/100
200/200 [==============================] - 1s 2ms/step - loss: 0.4207 - accuracy: 0.7972 - val_loss: 0.4120 - val_accuracy: 0.7975

In [113]:
y_log_2=model2.predict(X_test_scaled)

63/63 [==============================] - 0s 1ms/step


In [118]:
y_pred_2=np.where(y_log_2>0.5,1,0)

In [119]:
y_pred_2

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [120]:
print(classification_report(y_true=y_test,y_pred=y_pred_2))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1585
           1       0.79      0.47      0.59       415

    accuracy                           0.86      2000
   macro avg       0.83      0.72      0.76      2000
weighted avg       0.86      0.86      0.85      2000

